package gokorei.tanseki.service

import java.util.Properties

/**
 * The one release identity, read the same way by every seam that publishes it.
 *
 * `gradle.properties` holds the only editable copy of the version. The build
 * propagates it two ways:
 *
 * - as the `tanseki.version` system property, for the Gradle-driven paths (the
 *   OpenAPI export, the test suite, the `installDist` smoke runs);
 * - as `/tanseki-version.properties` on the runtime classpath, generated by the
 *   `:service:generateVersionResource` task, because a distribution launched by
 *   its start script has no system property to inherit.
 *
 * The MCP `initialize` response and the OpenAPI `info.version` both read
 * [value], so a dependent sees the same string whichever seam it speaks and
 * neither can drift onto a second hard-coded copy.
 */
object TansekiVersion {
    /** System property the build sets; wins over the packaged resource. */
    const val PROPERTY: String = "tanseki.version"

    private const val RESOURCE = "/tanseki-version.properties"

    /** Reported when neither source carries a version, e.g. a bare source checkout. */
    const val UNKNOWN: String = "0.0.0"

    val value: String
        get() =
            System.getProperty(PROPERTY)?.takeIf { it.isNotBlank() }
                ?: packaged()
                ?: UNKNOWN

    private fun packaged(): String? =
        TansekiVersion::class.java
            .getResourceAsStream(RESOURCE)
            ?.use { stream ->
                Properties()
                    .apply { load(stream) }
                    .getProperty("version")
                    ?.takeIf { it.isNotBlank() }
            }
}
